- name: create {{app_user}} user
  user:
    name: "{{app_user}}"
    comment: "{{app_name}} app user"
    generate_ssh_key: yes
    password: "{{app_user_password}}"
    shell: /bin/bash
    state: present

- name: authorize my SSH key to access {{app_user}}
  authorized_key:
    user: "{{app_user}}"
    key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"

- name: create the {{app_dir}} web app directory structure owned by {{app_user}}
  file:
    name: "{{item}}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: 0755
  with_items:
    - "{{app_dir}}"
    - "{{app_dir}}/shared"
    # The log directory must exist for nginx to consider the config valid
    - "{{app_dir}}/shared/log"

- name: install the latest packages needed by the {{app_name}} web app
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - autoconf
  - automake
  - bison
  - build-essential
  - curl
  - gawk
  - git
  - libffi-dev
  - libgdbm-dev
  - libgmp-dev
  - libncurses5-dev
  - libpq-dev
  - libreadline6-dev
  - libsqlite3-dev
  - libssl-dev
  - libtool
  - libyaml-dev
  - nodejs
  - pkg-config
  - ruby
  - sqlite3
  - wget
