- name: export foreman config
  command: >
    foreman export systemd /etc/systemd/system
      --app="{{foreman_app|quote}}"
      --log="{{foreman_log|quote}}"
      --user="{{foreman_user|quote}}"
      --root="{{foreman_root|quote}}"
      --procfile="{{foreman_procfile|quote}}"
  changed_when: yes
  become: yes
  notify:
  - reload systemd

- name: enable {{foreman_app}} systemd services
  command: systemctl enable /etc/systemd/system/{{foreman_app}}.target
  args:
    creates: "/etc/systemd/system/multi-user.target.wants/{{foreman_app}}.target"
  become: true

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  changed_when: yes
