letsencrypt_bin: /usr/bin/letsencrypt
letsencrypt_rsa_key_size: 4096
letsencrypt_dhparams_size: 2048
letsencrypt_email: "admin@{{letsencrypt_cert_domains[0]}}"
letsencrypt_webroot_path: "/var/www/letsencrypt-{{letsencrypt_cert_domains[0]}}"
letsencrypt_command: "{{letsencrypt_bin}} -n --agree-tos --rsa-key-size {{letsencrypt_rsa_key_size}} --text {% for domain in letsencrypt_cert_domains %}-d {{domain}} {% endfor %}--email {{letsencrypt_email}} {% if letsencrypt_server is defined %}--server {{ letsencrypt_server }}{% endif %} --expand"
letsencrypt_renewal_frequency:
  day: "*"
  hour: 0
  minute: 0
letsencrypt_renewal_command_args: '--renew-hook "systemctl reload nginx"'

# To use the staging server, specify:
# letsencrypt_server: https://acme-staging.api.letsencrypt.org/directory
