shared_dir: "{{app_dir}}/shared"
build_dir: "{{app_dir}}/versions/{{ansible_date_time.iso8601_micro | regex_replace(':', '_')}}"
bundle_dir: "vendor/bundle"
linked_dirs:
- "{{bundle_dir}}"
- public/assets
- tmp/cache
- tmp/pids
- tmp/sockets
- log
# Keep only the last 5 releases
keep_releases: 5
app_user_env_defaults:
  ANSIBLE_PROVISIONED: true
  APP_DIR: "{{app_dir}}"
  APP_ID: "{{app_name}}"
  APP_HOST: "{{app_host}}"
  DATABASE_URL: "postgresql://{{db_user}}:{{db_user_password|urlencode}}@{{db_host}}/{{db_name}}"
  MEMCACHE_SERVERS: "{{memcached_host}}:{{memcached_port}}"
  RACK_ENV: production
  RAILS_ENV: production
  # GC settings based on a tunemygc run on the Thredded Demo app:
  # https://tunemygc.com/heroku/07d7e2a5-51e4-4b19-821a-e62f590dcd30
  RUBY_GC_HEAP_INIT_SLOTS: "350000"
  RUBY_GC_HEAP_FREE_SLOTS: "1382037"
  RUBY_GC_HEAP_GROWTH_FACTOR: "1.035"
  RUBY_GC_HEAP_GROWTH_MAX_SLOTS: "50000"
  RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: "1.2"
  RUBY_GC_MALLOC_LIMIT: "29939911"
  RUBY_GC_MALLOC_LIMIT_MAX: "53891840"
  RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR: "1.32"
  RUBY_GC_OLDMALLOC_LIMIT: "24159191"
  RUBY_GC_OLDMALLOC_LIMIT_MAX: "43486544"
  RUBY_GC_OLDMALLOC_LIMIT_GROWTH_FACTOR: "1.2"
